// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import model "github.com/eclipse/che-plugin-broker/model"

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

// AddPlugin provides a mock function with given fields: plugin
func (_m *Storage) AddPlugin(plugin model.ChePlugin) error {
	ret := _m.Called(plugin)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.ChePlugin) error); ok {
		r0 = rf(plugin)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Plugins provides a mock function with given fields:
func (_m *Storage) Plugins() ([]model.ChePlugin, error) {
	ret := _m.Called()

	var r0 []model.ChePlugin
	if rf, ok := ret.Get(0).(func() []model.ChePlugin); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ChePlugin)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
